module:
  bid: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  content_moderation: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  image: 0
  media: 0
  media_library: 0
  node: 0
  notification: 0
  offer: 0
  options: 0
  page_cache: 0
  path_alias: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  workflows: 0
  views: 10
  minimal: 1000
theme:
  stark: 0
  claro: 0
  gin: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
