preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: horizontal
icon_default: true
icon_path: ''
high_contrast_mode: false
show_user_theme_settings: false
third_party_settings:
  shortcut:
    module_link: true
_core:
  default_config_hash: 7R74wb0NllX6DTTAV9sfg790XV_QXshmF0wAobLEFNQ
features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
favicon:
  use_default: true
accent_color: ''
focus_color: ''
icon_upload: ''
